= GeoRSS 1.0 Conformance Test Suite

== Scope

This executable test suite (ETS) verifies the conformance of the implementation
under test (IUT) with respect to the set of OGC GeoRSS 1.0 standard. Conformance testing is a kind of "black box" testing that examines the externally visible characteristics or behaviors of the IUT while disregarding any implementation details.

This release of the ETS implements a single conformance class called *Core* that tests for conformance to:

- Simple GeoRSS
- GeoRSS Profile of GML 3.1.1

== Test requirements

The documents listed below stipulate requirements that must be satisfied by a 
conforming implementation.

1. http://docs.opengeospatial.org/cs/17-002r1/17-002r1.html[OGC 17-002r1, OGC GeoRSS Encoding Standard 1.0]

== Test suite structure

The test suite definition file (testng.xml) is located in the root package, 
`org.opengis.cite.georss10`. A conformance class corresponds to a &lt;test&gt; element, each
of which includes a set of test classes that contain the actual test methods. 
The general structure of the test suite is shown in Table 1.

.Test suite structure
[cols="2,6a",options=header]
|===
|Conformance class
|Test classes and methods

|Simple GeoRSS
|org.opengis.cite.georss10.core.Georss11ValidationTests.docHasValidSimpleGeoRSSElements()

|GeoRSS Profile of GML 3.1.1
|org.opengis.cite.georss10.core.Georss11ValidationTests.docHasValidGMLGeoRSSElements()

|===

The Javadoc documentation provides more detailed information about the test 
methods that constitute the suite.

include::how-to-run-the-tests.adoc[]

== Using the REST API

Using the REST API of the TEAM Engine requires some run arguments. These ate summarized in Table 2.
The _Obligation_ descriptor can have the following values: M (mandatory), O (optional), or C (conditional).

.Test run arguments
[cols="1,1,1,6",options=header]
|===
|Name
|Value domain
|Obligation
|Description

|iut
|URI
|M
|A URI that refers to the implementation under test or metadata about it. Ampersand ('&amp;') characters must be percent-encoded as '%26'.

|===
